# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171122_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilePicture',
            field=models.FileField(default='static/img/propic/blank.png', upload_to='static/img/propic/'),
        ),
    ]
