# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171122_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='CouponCode',
            new_name='couponCode',
        ),
    ]
