# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171122_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor')),
            ],
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='CouponCode',
            new_name='couponCode',
        ),
    ]
