# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171122_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
