# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 03:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20171122_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPayable', models.FloatField()),
                ('bookingID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='p_bookingID', to='main.Booking')),
                ('receiverID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='p_receiverID', to=settings.AUTH_USER_MODEL)),
                ('senderID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='p_senderID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Add Value', 'Add Value'), ('Refund', 'Refund'), ('Tutorial Payment', 'Tutorial Payment'), ('Tutorial Salary', 'Tutorial Salary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 3, 6, 20, 824880, tzinfo=utc)),
        ),
    ]
