# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='propic',
            field=models.FileField(upload_to='static/img/propic/'),
        ),
    ]
