# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Add Value', 'Add Value'), ('Refund', 'Refund'), ('Tutorial Payment', 'Tutorial Payment'), ('Tutorial Salary', 'Tutorial Salary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 41, 52, 908000, tzinfo=utc)),
        ),
    ]
