# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171123_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 3, 18, 2, 346000, tzinfo=utc)),
        ),
    ]
