# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171123_1106'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutor',
            managers=[
                ('objectManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 4, 34, 30, 618684, tzinfo=utc)),
        ),
    ]
