# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171101_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_payable',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutoring_fee',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
