# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171101_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_date',
            field=models.DateField(),
        ),
    ]
