# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171123_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ptype',
            field=models.CharField(choices=[('Tutorial Payment', 'Tutorial Payment')], default='Tutorial Payment', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bookingID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_bookingID', to='main.Booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Add Value', 'Add Value'), ('Refund', 'Refund'), ('Tutorial Payment', 'Tutorial Payment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 10, 7, 27, 996818, tzinfo=utc)),
        ),
    ]
