# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171123_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 47, 10, 23000, tzinfo=utc)),
        ),
    ]
