# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171101_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_student', to='main.myUser'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_tutor', to='main.myUser'),
        ),
    ]
