# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171124_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 25, 7, 53, 57, 774313, tzinfo=utc)),
        ),
    ]
