# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171125_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 25, 8, 12, 3, 922574, tzinfo=utc)),
        ),
    ]
