# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171101_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
