# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tutor_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FullSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HalfSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions', models.ManyToManyField(to='main.FullSession')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Private', 'Private')], default='Private', max_length=20),
        ),
        migrations.AddField(
            model_name='privatesession',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor'),
        ),
        migrations.AddField(
            model_name='contractsession',
            name='sessions',
            field=models.ManyToManyField(to='main.HalfSession'),
        ),
        migrations.AddField(
            model_name='contractsession',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor'),
        ),
    ]
