# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171123_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ptype',
            field=models.CharField(choices=[('Tutorial Payment', 'Tutorial Payment')], default='Tutorial Payment', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 12, 22, 19, 236000, tzinfo=utc)),
        ),
    ]
