# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171101_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionDate', models.DateField(blank=True, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('EndTime', models.TimeField(blank=True, null=True)),
                ('Status', models.CharField(default='DEFAULTSTATUS', max_length=30)),
                ('Buttonid', models.CharField(default='00000000000000', max_length=14)),
            ],
        ),
    ]
