# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171123_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bookingID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_bookingID', to='main.Booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 12, 25, 18, 716000, tzinfo=utc)),
        ),
    ]
