# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsession',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='contractsession',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='privatesession',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='privatesession',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='ContractSession',
        ),
        migrations.DeleteModel(
            name='FullSession',
        ),
        migrations.DeleteModel(
            name='HalfSession',
        ),
        migrations.DeleteModel(
            name='PrivateSession',
        ),
    ]
