# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171124_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 9, 8, 50, 254000, tzinfo=utc)),
        ),
    ]
