# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171124_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 9, 56, 42, 902000, tzinfo=utc)),
        ),
    ]
