# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20171125_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ptype',
            field=models.CharField(choices=[('Tutorial Payment', 'Tutorial Payment')], default='Tutorial Payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Add Value', 'Add Value'), ('Tutorial Payment', 'Tutorial Payment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Holding up by MyTutor', 'Holding up by MyTutor'), ('Transferred', 'Transferred'), ('Cancelled', 'Cancelled')], default='Holding up by MyTutor', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 19, 15, 46, 660959, tzinfo=utc)),
        ),
    ]
