# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171125_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='studentID',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutorID',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Tutor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 20, 59, 14, 285337, tzinfo=utc)),
        ),
    ]
