# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171125_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 25, 17, 52, 8, 282000, tzinfo=utc)),
        ),
    ]
