# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171125_1300'),
        ('main', '0027_auto_20171126_0152'),
    ]

    operations = [
    ]
