# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20171126_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 12, 52, 29, 726624, tzinfo=utc)),
        ),
    ]
